### ISSUE TITLE
app.py中有一处代码异常 if isinstance(r, int) and t >= 100 and t < 600:

### ISSUE THREAD

**Issue by CoolerMe** [yzyly1992/2019_Python_Web_Dev#1]
if isinstance(r, int) and t >= 100 and t < 600:
这个t,在代码中是什么意思呢?请问

**Comment by qving11** [comment]
这个应该是if isinstance(r, int) and r >= 100 and r < 600:
是typo——廖老师的源代码中的typo。
它代表了HTTP状态码。比如200就是OK（有一节廖老师讲过的）

**Comment by yzyly1992** [comment]
谢谢提醒，已修正
